services:
    alsciende_serializer.object_manager:
        class: Alsciende\SerializerBundle\Manager\ObjectManager
        arguments: ["@doctrine.orm.entity_manager"]
    
    alsciende_serializer.source_ordering_service:
        class: Alsciende\SerializerBundle\Service\SourceOrderingService
        arguments: ["@alsciende_serializer.object_manager"]

    alsciende_serializer.scanning_service:
        class: Alsciende\SerializerBundle\Service\ScanningService
        arguments:
        - "@alsciende_serializer.object_manager"
        - "@alsciende_serializer.source_ordering_service"
        - "@annotation_reader"
        - "@cache.app"
        - "%alsciende_serializer.path%"

    alsciende_serializer.storing_service:
        class: Alsciende\SerializerBundle\Service\StoringService
        arguments: []

    alsciende_serializer.encoding_service:
        class: Alsciende\SerializerBundle\Service\EncodingService
        arguments: []

    alsciende_serializer.normalizing_service:
        class: Alsciende\SerializerBundle\Service\NormalizingService
        arguments: ["@alsciende_serializer.object_manager"]

    alsciende_serializer.serializer:
        class: Alsciende\SerializerBundle\Serializer\Serializer
        arguments: 
            - "@alsciende_serializer.storing_service"
            - "@alsciende_serializer.encoding_service"
            - "@alsciende_serializer.normalizing_service"
            - "@alsciende_serializer.object_manager"
