services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    alsciende_serializer.object_manager:
        class: Alsciende\SerializerBundle\Doctrine\ObjectManager
        arguments:
            - "@doctrine.orm.entity_manager"

    alsciende_serializer.source_ordering_service:
        class: Alsciende\SerializerBundle\Scan\SourceOrderingService
        arguments:
            - "@alsciende_serializer.object_manager"

    alsciende_serializer.scanning_service:
        class: Alsciende\SerializerBundle\Scan\ScanningService
        arguments:
            - "@alsciende_serializer.object_manager"
            - "@alsciende_serializer.source_ordering_service"
            - "@annotation_reader"
            - "@cache.app"
            - "%alsciende_serializer.path%"

    alsciende_serializer.storing_service:
        class: Alsciende\SerializerBundle\Store\StoringService

    alsciende_serializer.encoding_service:
        class: Alsciende\SerializerBundle\Encode\EncodingService

    alsciende_serializer.normalizing_service:
        class: Alsciende\SerializerBundle\Normalize\NormalizingService
        arguments:
            - "@alsciende_serializer.object_manager"

    alsciende_serializer.serializer:
        class: Alsciende\SerializerBundle\Serializer
        arguments: 
            - "@alsciende_serializer.storing_service"
            - "@alsciende_serializer.encoding_service"
            - "@alsciende_serializer.normalizing_service"
            - "@alsciende_serializer.object_manager"
