---
language: php
php:
  - '7.0'
  - '7.1'
sudo: false
cache:
  directories:
  - "$HOME/.composer/cache/files"
install:
  - composer install
script:
  - php vendor/bin/phpstan analyse src --configuration phpstan.neon --level 7
  - php vendor/bin/phpunit
